### ISSUE TITLE
Ping - Zertrin

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#25]
Coucou @zertrin,

Petite vérification comme ça fait deux ans (voir #9). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by zertrin** [comment]
Coucou @remram44, oui c'est toujours à jour 😁
Bonne idée de demander régulièrement 🙂

**Comment by remram44** [comment]
Autant essayer d'être à jour :blush:
Mais ce serait plus facile si c'était un peu automatique

**Comment by remram44** [comment]
Coucou @zertrin,

Encore deux ans ! Es-tu toujours au même endroit ?

**Comment by zertrin** [comment]
Hey @remram44 :smile:
Oui toujours à Singapour :wink:
