### ISSUE TITLE
Ping - Ryen

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#27]
Coucou @RChaintreuil,

Petite vérification comme ça fait deux ans (voir #10). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by RChaintreuil** [comment]
Salut Remram ! Yep, toujours au même endroit !

Merci,
Remi

**Comment by remram44** [comment]
Coucou @RChaintreuil,

Encore deux ans ! Es-tu toujours au même endroit ?

**Comment by RChaintreuil** [comment]
Salut @remram44 , toujours au même endroit oui !
