### ISSUE TITLE
Ping - BackIsBachus

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#36]
Coucou @BackIsBachus,

Petite vérification comme ça fait deux ans (voir #14). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by ghost** [comment]
Salut,
Vi je suis toujours au même endroit, à la limite j'irai ajuster légèrement l'endroit vu que ça pointe pas exactement le bon endroit mais c'est tout.
