### ISSUE TITLE
Ping - warp

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#38]
Coucou @spascou,

Petite vérification comme ça fait deux ans (voir #15). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by spascou** [comment]
Yo !

Oui, toujours au meme endroit :)

**Comment by remram44** [comment]
Tant que ça te plait, comme endroit :wink:
