### ISSUE TITLE
Ping - Th3oSMith

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#40]
Coucou @th3oSMith,

Petite vérification comme ça fait deux ans (voir #16). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by th3oSMith** [comment]
Coucou,

Avec beaucoup de retard j'ai fait créé une PR #48.

C'est sympa que tu maintiennes la carte :)
