### ISSUE TITLE
Ping - Fitz

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#49]
Coucou @vfauth,

Petite vérification comme ça fait deux ans (voir #31). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by vfauth** [comment]
Hello,

J'ai créé une PR, merci pour le rappel :)
