### ISSUE TITLE
Ping - redlink

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#50]
Coucou @Redlinkk,

Petite vérification comme ça fait deux ans (voir #30). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by Redlinkk** [comment]
Salut ! Merci pour le rappel. Je suis toujours au même endroit, pas de changement nécessaire :)
