### ISSUE TITLE
Ping - Gagou

### ISSUE THREAD

**Issue by remram44** [supelec-rezo/map#52]
Coucou @GagouKun,

Petite vérification comme ça fait deux ans (voir #32). Es-tu toujours au même endroit ? Réponds ici ou ouvre une Pull Request. À ta demande ou si tu ne réponds pas, je ne te mentionerai plus pour pas spammer.

Merci

**Comment by olivgat** [comment]
Salut @remram44 ,

Rien de changé pour moi, toujours sur Lyon :)
